name: Retrieve latest translations from Tolgee

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  main:
    runs-on: windows-latest
    env:
        TOLGEE_KEY: '${{ secrets.TOLGEE_TOKEN }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download Tolgee translations
        run: |
          cd elevenclock/lang
          python download_translations.py --autocommit
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          author: "Tolgee Bot <tolgee-bot@users.noreply.github.com>"
          commit-message: "[BOT] Load updated translations from Tolgee"
